# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import touhou_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouhouTrackerColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_hrtp', models.CharField(default='#f44336', max_length=7)),
                ('c_soew', models.CharField(default='#E91E63', max_length=7)),
                ('c_podd', models.CharField(default='#9C27B0', max_length=7)),
                ('c_lls', models.CharField(default='#673AB7', max_length=7)),
                ('c_ms', models.CharField(default='#3F51B5', max_length=7)),
                ('c_eosd', models.CharField(default='#2196F3', max_length=7)),
                ('c_pcb', models.CharField(default='#03A9F4', max_length=7)),
                ('c_in', models.CharField(default='#00BCD4', max_length=7)),
                ('c_mof', models.CharField(default='#009688', max_length=7)),
                ('c_sa', models.CharField(default='#4CAF50', max_length=7)),
                ('c_ufo', models.CharField(default='#8BC34A', max_length=7)),
                ('c_td', models.CharField(default='#CDDC39', max_length=7)),
                ('c_ddc', models.CharField(default='#FFEB3B', max_length=7)),
                ('c_lolk', models.CharField(default='#FFC107', max_length=7)),
                ('c_hsifs', models.CharField(default='#FF9800', max_length=7)),
                ('c_pofv', models.CharField(default='#FF5722', max_length=7)),
                ('c_gfw', models.CharField(default='#795548', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TouhouTrackerTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(default=touhou_tracker.models.my_random_key, max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('read_only', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touhou_tracker.TouhouTrackerColors')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='touhou_tracker.TouhouTrackerTrack')),
            ],
        ),
    ]
