# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touhou_tracker', '0002_track_track_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_hrtp', models.CharField(default='#f44336', max_length=6)),
                ('c_soew', models.CharField(default='#E91E63', max_length=6)),
                ('c_podd', models.CharField(default='#9C27B0', max_length=6)),
                ('c_lls', models.CharField(default='#673AB7', max_length=6)),
                ('c_ms', models.CharField(default='#3F51B5', max_length=6)),
                ('c_eosd', models.CharField(default='#2196F3', max_length=6)),
                ('c_pcb', models.CharField(default='#03A9F4', max_length=6)),
                ('c_in', models.CharField(default='#00BCD4', max_length=6)),
                ('c_mof', models.CharField(default='#009688', max_length=6)),
                ('c_sa', models.CharField(default='#4CAF50', max_length=6)),
                ('c_ufo', models.CharField(default='#8BC34A', max_length=6)),
                ('c_td', models.CharField(default='#CDDC39', max_length=6)),
                ('c_ddc', models.CharField(default='#FFEB3B', max_length=6)),
                ('c_lolk', models.CharField(default='#FFC107', max_length=6)),
                ('c_hsifs', models.CharField(default='#FF9800', max_length=6)),
                ('c_pofv', models.CharField(default='#FF5722', max_length=6)),
                ('c_gfw', models.CharField(default='#795548', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='colors',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='touhou_tracker.Colors'),
            preserve_default=False,
        ),
    ]
