# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touhou_tracker', '0003_auto_20170622_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
